<?xml version="1.0" encoding="utf-8"?><Database Name="stock" Class="DataClasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PAVILION\SQLEXPRESS;Initial Catalog=stock;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="stockConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[save]" Member="saves">
    <Type Name="save">
      <Column Name="SL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileLocation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>